# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lock.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lock.proto',
  package='lock',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nlock.proto\x12\x04lock\"\x0e\n\x0cGlockRequest\" \n\rGlockResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2o\n\x05GLOCK\x12\x33\n\x06Unlock\x12\x12.lock.GlockRequest\x1a\x13.lock.GlockResponse\"\x00\x12\x31\n\x04Lock\x12\x12.lock.GlockRequest\x1a\x13.lock.GlockResponse\"\x00\x62\x06proto3')
)




_GLOCKREQUEST = _descriptor.Descriptor(
  name='GlockRequest',
  full_name='lock.GlockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=34,
)


_GLOCKRESPONSE = _descriptor.Descriptor(
  name='GlockResponse',
  full_name='lock.GlockResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='lock.GlockResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['GlockRequest'] = _GLOCKREQUEST
DESCRIPTOR.message_types_by_name['GlockResponse'] = _GLOCKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GlockRequest = _reflection.GeneratedProtocolMessageType('GlockRequest', (_message.Message,), dict(
  DESCRIPTOR = _GLOCKREQUEST,
  __module__ = 'lock_pb2'
  # @@protoc_insertion_point(class_scope:lock.GlockRequest)
  ))
_sym_db.RegisterMessage(GlockRequest)

GlockResponse = _reflection.GeneratedProtocolMessageType('GlockResponse', (_message.Message,), dict(
  DESCRIPTOR = _GLOCKRESPONSE,
  __module__ = 'lock_pb2'
  # @@protoc_insertion_point(class_scope:lock.GlockResponse)
  ))
_sym_db.RegisterMessage(GlockResponse)



_GLOCK = _descriptor.ServiceDescriptor(
  name='GLOCK',
  full_name='lock.GLOCK',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=70,
  serialized_end=181,
  methods=[
  _descriptor.MethodDescriptor(
    name='Unlock',
    full_name='lock.GLOCK.Unlock',
    index=0,
    containing_service=None,
    input_type=_GLOCKREQUEST,
    output_type=_GLOCKRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Lock',
    full_name='lock.GLOCK.Lock',
    index=1,
    containing_service=None,
    input_type=_GLOCKREQUEST,
    output_type=_GLOCKRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GLOCK)

DESCRIPTOR.services_by_name['GLOCK'] = _GLOCK

# @@protoc_insertion_point(module_scope)
